
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mirko
      POSTGRES_DB: EA
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - backend-network

  backend:
    build: .
    env_file:
      - .env
    container_name: enterprise_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/EA
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mirko
    ports:
      - "8080:8080"
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge