package application;

public enum Block{MONETA,VELOCITA,SCUDO,LENTEZZA,VITA,VUOTO,TERRA,PERSONAGGIO,MURO,ERBA,SPECIALE,TUBO,BARILE,FINE,PORTALE,PONTE,MORTE,USATO,MINIZOMBIE,CREEPER,SKELETON,FRECCIA,BOSS,FIREBALL}